services:
  coturn:
    image: coturn/coturn:4.6.2
    network_mode: host
    command:
      - -n
      - --log-file=stdout
      - --min-port=49160
      - --max-port=49200
      - --lt-cred-mech
      - --user=repro:repro
      - --realm=repro.local
      - --no-tls
      - --no-dtls
      - --no-cli
